"""Fernet wrapper for DSN encryption-at-rest (#51).

The connections table stores DSNs as Fernet ciphertext — even a leak of
the metrics SQLite file shouldn't expose database credentials. The key
itself lives outside the database, so "compromise of the DB file" and
"compromise of the key" are independent events.

Behavior by environment:
- ``FERNET_KEY`` set in the process environment → use it.
- ``FERNET_KEY`` unset in the process environment but present in ``.env`` →
  use it in both development and production.
- ``FERNET_KEY`` absent from both the process environment and ``.env``,
  and ``FLASK_ENV`` ≠ production → use ``.env.local`` if present; otherwise
  generate a key, write it to ``.env.local``, and log a loud warning.
- ``FERNET_KEY`` absent from both the process environment and ``.env``,
  and production → raise ``FernetKeyMissing``. ``.env.local`` is never used
  in production.
"""

from __future__ import annotations

import logging
import os
import threading
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken

from .config import is_production

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).resolve().parent.parent
_ENV = _REPO_ROOT / ".env"
_ENV_LOCAL = _REPO_ROOT / ".env.local"

_fernet: Fernet | None = None
_lock = threading.Lock()


class FernetKeyMissing(RuntimeError):
    """Raised when FERNET_KEY is required (production) but absent."""


def _load_key() -> bytes:
    """Read the key from the environment or dotenv files.

    ``.env`` is allowed in every environment. ``.env.local`` is a development
    fallback only. Generated development keys are persisted to ``.env.local``
    so the same process (and its restarts) keeps decrypting what it encrypted.
    """
    raw = os.environ.get("FERNET_KEY")
    if raw:
        return raw.encode("ascii") if isinstance(raw, str) else raw

    from_env_file = _load_key_from_dotenv(_ENV)
    if from_env_file:
        os.environ["FERNET_KEY"] = from_env_file.decode("ascii")
        return from_env_file

    if is_production():
        raise FernetKeyMissing(
            "FERNET_KEY must be set in production — refusing to generate a "
            "throwaway key. See .env.example."
        )

    existing = _load_key_from_dotenv(_ENV_LOCAL)
    if existing:
        os.environ["FERNET_KEY"] = existing.decode("ascii")
        return existing

    # Dev fallback: generate, persist, warn.
    new_key = Fernet.generate_key()
    try:
        with _ENV_LOCAL.open("a", encoding="utf-8") as f:
            f.write(
                f"\n# Auto-generated by app/crypto.py — first dev run\nFERNET_KEY={new_key.decode()}\n"
            )
    except OSError:
        # Read-only FS (e.g. Docker image) — proceed with in-memory key.
        # Operator MUST set FERNET_KEY for any persistent deployment.
        logger.warning(
            "FERNET_KEY not set and could not write .env.local — using "
            "in-memory key. Stored DSNs will be unreadable after restart."
        )
        return new_key

    logger.warning(
        "FERNET_KEY auto-generated and written to %s. SET IT EXPLICITLY "
        "via env var for any non-trivial deployment.",
        _ENV_LOCAL,
    )
    # Propagate to the current process so the next caller sees it via env.
    os.environ["FERNET_KEY"] = new_key.decode()
    return new_key


def _load_key_from_dotenv(path: Path) -> bytes | None:
    """Return the last FERNET_KEY from a dotenv file, if present.

    Local CLI scripts should use the same key as docker-compose (``.env``)
    before falling back to ``.env.local``; otherwise they can re-encrypt DSNs
    with a key the app container does not know.
    """
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return None

    for line in reversed(lines):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if not stripped.startswith("FERNET_KEY="):
            continue

        value = stripped.split("=", 1)[1].strip().strip("\"'")
        if value:
            return value.encode("ascii")

    return None


def _get_fernet() -> Fernet:
    """Lazy-init singleton — first call may write .env.local (dev only)."""
    global _fernet

    if _fernet is None:
        with _lock:
            if _fernet is None:
                _fernet = Fernet(_load_key())

    return _fernet


def validate_fernet_key() -> None:
    """Validate that the configured Fernet key can be used."""
    Fernet(_load_key())


def encrypt_dsn(plain: str) -> bytes:
    """Encrypt a DSN string to bytes. Empty input is a programming error."""
    if not plain:
        raise ValueError("Cannot encrypt empty DSN")
    return _get_fernet().encrypt(plain.encode("utf-8"))


def decrypt_dsn(ciphertext: bytes) -> str:
    """Decrypt previously-encrypted DSN.

    Raises ``InvalidToken`` if the ciphertext was produced by a different
    key (e.g. after key rotation without re-encryption) or if the input is
    corrupted.
    """
    if not ciphertext:
        raise ValueError("Cannot decrypt empty ciphertext")
    return _get_fernet().decrypt(ciphertext).decode("utf-8")


# Telegram bot tokens (#143) — encrypted with the same Fernet key as DSNs.
# Separate functions for readability at call sites; same wire format so a
# future key-rotation tool can re-encrypt everything in one sweep.


def encrypt_token(plain: str) -> bytes:
    """Encrypt a Telegram bot token (or any secret string)."""
    if not plain:
        raise ValueError("Cannot encrypt empty token")
    return _get_fernet().encrypt(plain.encode("utf-8"))


def decrypt_token(ciphertext: bytes) -> str:
    """Decrypt a Telegram bot token previously stored via ``encrypt_token``."""
    if not ciphertext:
        raise ValueError("Cannot decrypt empty ciphertext")
    return _get_fernet().decrypt(ciphertext).decode("utf-8")


def reset_for_tests() -> None:
    """Drop the cached Fernet so tests can swap keys per-test via env."""
    global _fernet

    with _lock:
        _fernet = None


__all__ = [
    "FernetKeyMissing",
    "InvalidToken",
    "decrypt_dsn",
    "decrypt_token",
    "encrypt_dsn",
    "encrypt_token",
    "reset_for_tests",
    "validate_fernet_key",
]
