"""Copy a SQLite metrics store into a Postgres/TimescaleDB destination.

Reads every table written by app.metrics_storage (metrics, changepoints,
schema_snapshots, schema_events, anomaly_scores, drift_reports,
llm_explanations, telegram_throttle, notifications) from a source SQLite
file and replays it into the destination DSN through SQLAlchemy. The
destination schema is applied first via app.metrics_storage._apply_schema,
so this script also serves as a "create + load" bootstrap.

Idempotent on tables with a primary key — `INSERT ... ON CONFLICT DO UPDATE`
overwrites destination rows so a re-run reflects the freshest source state
(stale destination rows from earlier runs do not survive). The append-only
`metrics`, `schema_events` and `notifications` tables have no natural key
and will accumulate duplicates on re-run; use ``--reset`` to truncate them
before loading.

``--reset`` issues `TRUNCATE ... RESTART IDENTITY` on the destination's
append tables, which takes an `ACCESS EXCLUSIVE` lock. Take the app offline
before running with ``--reset`` to avoid blocking writers.

Usage:
    python -m scripts.migrate_metrics_to_timescale \\
        --source sqlite:///monitor.db \\
        --target postgresql://postgres:dev@localhost:5433/metrics
"""

from __future__ import annotations

import argparse
from collections.abc import Iterable
from datetime import UTC, datetime

from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

# Tables with a primary key — safe to re-run thanks to ON CONFLICT DO NOTHING.
_KEYED_TABLES: dict[str, tuple[list[str], list[str]]] = {
    "changepoints": (
        [
            "project_id",
            "ts",
            "table_name",
            "metric_name",
            "score",
            "value_before",
            "value_after",
            "detected_at",
        ],
        ["project_id", "ts", "table_name", "metric_name"],
    ),
    "schema_snapshots": (
        ["project_id", "table_name", "columns", "captured_at"],
        ["project_id", "table_name"],
    ),
    "anomaly_scores": (
        ["project_id", "ts", "table_name", "score", "is_anomaly"],
        ["project_id", "ts", "table_name"],
    ),
    "drift_reports": (
        [
            "project_id",
            "table_name",
            "column_name",
            "data_type",
            "psi",
            "ks_pvalue",
            "is_drift",
            "severity",
            "computed_at",
        ],
        ["project_id", "table_name", "column_name"],
    ),
    "llm_explanations": (
        ["table_name", "metric", "ts", "explanation", "suggested_fix", "confidence", "created_at"],
        ["table_name", "metric", "ts"],
    ),
    "telegram_throttle": (
        ["project_id", "table_name", "event_key", "last_sent_at"],
        ["project_id", "table_name", "event_key"],
    ),
    "users": (
        ["id", "email", "password_hash", "created_at", "last_login_at"],
        ["id"],
    ),
    "projects": (
        ["id", "user_id", "name", "slug", "created_at"],
        ["id"],
    ),
    "connections": (
        [
            "id",
            "project_id",
            "name",
            "dsn_encrypted",
            "schema_name",
            "interval_minutes",
            "is_active",
            "created_at",
        ],
        ["id"],
    ),
}

# Append-only tables — no PK, idempotency requires --reset.
_APPEND_TABLES: dict[str, list[str]] = {
    "metrics": ["project_id", "ts", "table_name", "metric_name", "value", "tags"],
    "schema_events": ["ts", "table_name", "change_type", "column_name", "details", "project_id"],
    # `id` is regenerated by the destination (BIGSERIAL) — don't copy it over.
    "notifications": [
        "ts",
        "project_id",
        "event_type",
        "table_name",
        "metric_name",
        "message",
        "status",
        "error",
        "chat_id",
    ],
    "failed_login_attempts": ["email", "attempted_at"],
}

_BATCH_SIZE = 1000
# Commit every N batches. One single transaction over a 1M-row source
# accumulates a multi-GB WAL on the destination and holds locks for the
# whole run; smaller commits trade a bit of throughput for bounded WAL
# growth and resumable progress on failure.
_COMMIT_EVERY = 10


def _source_columns(src: Engine, table: str) -> set[str]:
    """Return column names that actually exist in a SQLite source table."""
    with src.connect() as conn:
        rows = conn.execute(text(f"PRAGMA table_info({table})")).fetchall()
    return {row[1] for row in rows}


def _select(src: Engine, table: str, columns: list[str]) -> Iterable[dict]:
    """SELECT requested columns from source.

    project_id is substituted with 'legacy' when absent — the column was added
    in a later migration and old SQLite sources default to the legacy tenant.
    Any other missing column raises immediately to surface schema incompatibility.
    """
    present = _source_columns(src, table)
    missing = [c for c in columns if c not in present and c != "project_id"]
    if missing:
        raise ValueError(
            f"Source table '{table}' is missing expected columns: {missing}. "
            "Run the source DB through _migrate_existing_schema() first."
        )
    parts = [col if col in present else f"'legacy' AS {col}" for col in columns]
    sql = text(f"SELECT {', '.join(parts)} FROM {table}")
    with src.connect() as conn:
        result = conn.execution_options(stream_results=True).execute(sql)
        for row in result:
            yield dict(zip(columns, row, strict=True))


def _insert_keyed(
    dst: Engine, table: str, columns: list[str], conflict: list[str], rows: Iterable[dict]
) -> int:
    cols = ", ".join(columns)
    placeholders = ", ".join(f":{c}" for c in columns)
    conflict_cols = ", ".join(conflict)
    update_cols = [c for c in columns if c not in conflict]
    if update_cols:
        set_clause = ", ".join(f"{c} = EXCLUDED.{c}" for c in update_cols)
        on_conflict = f"ON CONFLICT ({conflict_cols}) DO UPDATE SET {set_clause}"
    else:
        on_conflict = f"ON CONFLICT ({conflict_cols}) DO NOTHING"
    sql = text(f"INSERT INTO {table} ({cols}) VALUES ({placeholders}) {on_conflict}")
    return _insert_batched(dst, sql, rows)


def _insert_append(dst: Engine, table: str, columns: list[str], rows: Iterable[dict]) -> int:
    cols = ", ".join(columns)
    placeholders = ", ".join(f":{c}" for c in columns)
    sql = text(f"INSERT INTO {table} ({cols}) VALUES ({placeholders})")
    return _insert_batched(dst, sql, rows)


def _insert_batched(dst: Engine, sql, rows: Iterable[dict]) -> int:
    """Execute *sql* in batches, committing every ``_COMMIT_EVERY`` batches."""
    total = 0
    batch: list[dict] = []
    batches_since_commit = 0
    conn = dst.connect()
    txn = conn.begin()
    try:
        for row in rows:
            batch.append(row)
            if len(batch) >= _BATCH_SIZE:
                conn.execute(sql, batch)
                total += len(batch)
                batch.clear()
                batches_since_commit += 1
                if batches_since_commit >= _COMMIT_EVERY:
                    txn.commit()
                    txn = conn.begin()
                    batches_since_commit = 0
        if batch:
            conn.execute(sql, batch)
            total += len(batch)
        txn.commit()
    except Exception:
        txn.rollback()
        raise
    finally:
        conn.close()
    return total


def _truncate(dst: Engine, tables: list[str]) -> None:
    """TRUNCATE the named tables on the destination."""
    if not tables:
        return
    with dst.begin() as conn:
        conn.execute(text("TRUNCATE " + ", ".join(tables) + " RESTART IDENTITY"))


def _apply_destination_schema(target_url: str) -> None:
    """Bootstrap the Timescale schema on the target.

    Reuses app.metrics_storage._apply_schema by temporarily pointing the
    settings at the target URL — keeps the script in sync with whatever
    schema the running app would create.
    """
    from app import metrics_storage
    from app.config import settings as app_settings

    original = app_settings.MONITOR_DB_URL
    app_settings.MONITOR_DB_URL = target_url
    metrics_storage._engine = None
    metrics_storage._initialized = False
    try:
        metrics_storage.get_engine()
    finally:
        app_settings.MONITOR_DB_URL = original
        metrics_storage._engine = None
        metrics_storage._initialized = False


def migrate(source_url: str, target_url: str, *, reset_append: bool = False) -> dict[str, int]:
    """Copy all metrics-store tables from `source_url` to `target_url`.

    Returns a dict of {table_name: rows_copied}.
    """
    _apply_destination_schema(target_url)

    src = create_engine(source_url, future=True)
    dst = create_engine(target_url, future=True)

    if reset_append:
        _truncate(dst, list(_APPEND_TABLES))

    counts: dict[str, int] = {}
    for table, (cols, conflict) in _KEYED_TABLES.items():
        counts[table] = _insert_keyed(dst, table, cols, conflict, _select(src, table, cols))
    for table, cols in _APPEND_TABLES.items():
        counts[table] = _insert_append(dst, table, cols, _select(src, table, cols))

    src.dispose()
    dst.dispose()
    return counts


def main() -> None:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "--source",
        default="sqlite:///monitor.db",
        help="Source SQLite DSN (default: sqlite:///monitor.db).",
    )
    p.add_argument(
        "--target",
        required=True,
        help="Destination Postgres/TimescaleDB DSN.",
    )
    p.add_argument(
        "--reset",
        action="store_true",
        help="TRUNCATE append-only tables (metrics, schema_events, notifications) "
        "before loading. Without this, re-runs duplicate rows in those tables.",
    )
    args = p.parse_args()

    start = datetime.now(UTC)
    counts = migrate(args.source, args.target, reset_append=args.reset)
    elapsed = (datetime.now(UTC) - start).total_seconds()

    print(f"Migration complete in {elapsed:.1f}s:")
    for table, n in counts.items():
        print(f"  {table:20s} {n:>10,} rows")


if __name__ == "__main__":
    main()
